#!/bin/bash

./cmakegen-gcc-x64-release

BUILD_DIR=../build/gcc-x64-release
pushd $BUILD_DIR

# Run build.
echo "[*] Build is running..."
cmake --build . --config Release --target package

# Exit
echo "[*] Project build succeeded!"
popd

